title: 4th Workshop on Foundation Models for Social Good
# description:  2026
timezone: United Kingdom/Liverpool
baseurl: "/NSG-2026"
# logo: assets/css/NSG.png

navigation:
  Home: "/"
  Call for Papers: "cfp.html"
  Accepted Papers: "papers.html"
  Speakers: "speakers.html"
  Programme: "programme.html"
  Organizers: "organizers.html"
  Past Events: "past.html"
show_downloads: false
